### ISSUE TITLE
Reduce image size by adding "yum clean all"

### ISSUE THREAD

**Issue by sujaypillai** [Alfresco/alfresco-docker-base-java#23]
Noticed that just adding "yum clean all" to existing  "yum -y update" https://github.com/Alfresco/alfresco-docker-base-java/blob/f3de686ef40663395057c0441cb6dbe62272bb72/Dockerfile#L13

> RUN yum -y update \
    nss-3.36.0-5.el7_5 \
    bind-license-9.9.4-61.el7 \ 
    curl-7.29.0-46.el7 \
    systemd-219-57.el7 \
    glibc-2.17-222.el7 \
    openssl-libs-1.0.2k-12.el7 \
    krb5-libs-1.15.1-19.el7 \
    libgcc-4.8.5-28.el7_5.1 \
    libstdc++-4.8.5-28.el7_5.1 \
    procps-ng-3.3.10-17.el7_5.2 && yum clean all

helps in reducing image size from 512Mb to 461Mb for JRE 10.

**Comment by melahn** [comment]
@jottley Looks good.  Thanks for raising the issue @sujaypillai
