### ISSUE TITLE
Question concerning use of AdoptOpenJDK JRE

### ISSUE THREAD

**Issue by AFaust** [Alfresco/alfresco-docker-base-java#33]
Since the pull request #30 was eventually reverted / not accepted, the size of the Java Docker images is still quite large as they include a full JDK. Instead of using post-processing steps to trim down the size of the JDK - which was determined to be problematic from the licensing perspective - the image could simply use a JRE. Unfortunately, OpenJDK does not provide a JRE, but AdoptOpenJDK does (see https://adoptopenjdk.net/archive.html).
Before I invest time in preparing a PR for this and risking reversion again, I wanted to ask if this would be acceptable to Legal.

**Comment by melahn** [comment]
Axel, glad you asked in advance.  I'll be very honest with you. Going through another legal review cycle and then rebuilding/retesting the base Java image and all the other Alfresco images that derive from that is not a priority for us at the moment.  That could change if we begin to hear customer use cases for smaller, jre-based images.   So, I would suggest not spending time building a PR for this.
