### ISSUE TITLE
CentOS 8: Wrong encoding

### ISSUE THREAD

**Issue by ariksidney** [Alfresco/alfresco-docker-base-java#60]
Hi there,

I discovered that transforming a file from csv to pdf with alfresco-transform-misc and umlauts is not working properly. After digging a bit around, I saw that the default encoding which is picked up by Java on the CentOS 8 image is ANSI_X3.4-1968 instead of UTF-8.

To reproduce the issue: 

- Start a container from the alfresco-docker-base-java image (There will be some locale related warnings)
- When executing a simple Java method which prints System.getProperty("file.encoding"), ANSI_X3.4-1968 is returned instead of UTF-8.

I think adding the following environment variable to the Dockerfile should be enough to fix it.
`ENV LC_ALL C.UTF-8`

Thanks!

**Comment by mteodori** [comment]
I see that setting you mention though: https://github.com/Alfresco/alfresco-docker-base-java/blob/master/Dockerfile#L21

But only on Centos 8 images, if I run locally I can see:

```bash
docker run -it alfresco/alfresco-base-java:11.0.11-centos-8
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[root@8fb5737cc2b3 /]# 
```

**Comment by mteodori** [comment]
tracked internally at https://alfresco.atlassian.net/browse/OPSEXP-923
