### ISSUE TITLE
Provide multi-arch image with support for arm64

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-docker-base-java#79]
This image needs to evolve to provide arm64 builds for Alfresco docker images. The current limited/non-support is making it complicated for developers to use Alfresco docker images for customisation and product development on current ARM64 based machines.

**Comment by mteodori** [comment]
at the moment this is not a priority as we're not using any but happy to accept a PR if you can provide some automated way of verifying the fix maybe using AWS provided M1 mac machines https://aws.amazon.com/about-aws/whats-new/2021/12/amazon-ec2-m1-mac-instances-macos/

**Comment by mteodori** [comment]
tracked in OPSEXP-1167
